apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: homeassistant
  namespace: homeassistant
spec:
  parentRefs:
    - name: main-gateway
      namespace: gateway-api-system
  hostnames:
    - homeassistant.production.k8s.evoteum.com
  rules:
    - backendRefs:
        - name: homeassistant
          port: 8080
