apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-services
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/evoteum/kubernetes-lab-services.git
        revision: main
        files:
          - path: helm-charts.yaml
  template:
    metadata:
      name: "{{ name }}"
      labels:
        evoteum.dev/component: helm-service
      annotations:
        evoteum.dev/why: "{{ why }}"
    spec:
      project: default
      source:
        repoURL: "{{ chartRepo }}"
        chart: "{{ chartName }}"
        targetRevision: "{{ targetRevision }}"
        helm:
          releaseName: "{{ name }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ name }}"
        namespaceMetadata:
          labels:
            app.kubernetes.io/managed-by: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
