apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: planzoco
  namespace: argocd
  annotations:
    bumpCount: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/evoteum/planzoco.git
    targetRevision: main
    path: chart
    helm:
      releaseName: planzoco
  destination:
    server: https://kubernetes.default.svc
    namespace: planzoco
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
