apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grocy
  namespace: grocy
spec:
  parentRefs:
    - name: main-gateway
      namespace: gateway-api-system
  hostnames:
    - grocy.production.k8s.evoteum.com
  rules:
    - backendRefs:
        - name: grocy
          port: 80
