apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: pihole
  namespace: pihole
spec:
  parentRefs:
    - name: main-gateway
      namespace: gateway-api-system
  hostnames:
    - pihole.production.k8s.evoteum.com
  rules:
    - backendRefs:
        - name: pihole
          port: 80
