apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: privatebin
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://privatebin.github.io/helm-chart/
    chart: privatebin
    targetRevision: 0.23.4
  destination:
    server: https://kubernetes.default.svc
    namespace: privatebin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
