apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deluge
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://rubxkube.github.io/charts/
    chart: deluge
    targetRevision: 1.2.1
    helm:
      values: |
        common:
          persistence:
            enabled: true
            volumes:
              - name: "config"
                storageClassName: "ceph-block"
                size: "2Gi"
                pvcClaim: ""
                containerMount: "/config/"
              - name: "downloads"
                storageClassName: "ceph-block"
                size: "100Gi"
                pvcClaim: ""
                containerMount: "/downloads/"
  destination:
    server: https://kubernetes.default.svc
    namespace: deluge
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
