apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: deluge
  namespace: deluge
spec:
  parentRefs:
    - name: main-gateway
      namespace: gateway-api-system
  hostnames:
    - deluge.production.k8s.evoteum.com
  rules:
    - backendRefs:
        - name: deluge
          port: 8112
