apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: neo4j
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://neo4j.github.io/helm-charts/
    chart: neo4j-helm-charts/neo4j
    targetRevision: 2026.4.0
  destination:
    server: https://kubernetes.default.svc
    namespace: neo4j
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
