apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
spec:
  project: default
  source:
    repoURL: oci://ghcr.io/immich-app/immich-charts/immich
    chart: immich
    targetRevision: 0.12.0
    helm:
      values: |
        server:
          controllers:
            main:
              containers:
                main:
                  env:
                    DB_HOSTNAME: immich-postgres-rw
                    DB_DATABASE_NAME: immich
                    DB_USERNAME:
                      valueFrom:
                        secretKeyRef:
                          name: immich-postgres-credentials
                          key: username
                    DB_PASSWORD:
                      valueFrom:
                        secretKeyRef:
                          name: immich-postgres-credentials
                          key: password
        immich:
          persistence:
            library:
              existingClaim: immich-library
  destination:
    server: https://kubernetes.default.svc
    namespace: immich
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
