apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
spec:
  project: default

  source:
    repoURL: ghcr.io/immich-app/immich-charts
    chart: immich
    targetRevision: 0.13.1
    helm:
      releaseName: immich
      valuesObject:
        server:
          controllers:
            main:
              strategy: Recreate
              containers:
                main:
                  env:
                    DB_HOSTNAME:
                      valueFrom:
                        secretKeyRef:
                          name: immich-database-app
                          key: host
                    DB_DATABASE_NAME:
                      valueFrom:
                        secretKeyRef:
                          name: immich-database-app
                          key: dbname
                    DB_USERNAME:
                      valueFrom:
                        secretKeyRef:
                          name: immich-database-app
                          key: user
                    DB_PASSWORD:
                      valueFrom:
                        secretKeyRef:
                          name: immich-database-app
                          key: password

        valkey:
          enabled: true
          controllers:
            main:
              strategy: Recreate
          persistence:
            data:
              enabled: true
              type: persistentVolumeClaim
              size: 1Gi
              accessMode: ReadWriteOnce
              storageClass: ceph-block

        immich:
          persistence:
            library:
              existingClaim: immich-library

  destination:
    server: https://kubernetes.default.svc
    namespace: immich

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true