apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-postgres-credentials
  namespace: immich
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: immich-postgres-credentials
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: secret/immich/postgres
        property: username
    - secretKey: password
      remoteRef:
        key: secret/immich/postgres
        property: password