apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kavita
  namespace: kavita
spec:
  parentRefs:
    - name: main-gateway
      namespace: gateway-api-system
  hostnames:
    - kavita.production.k8s.evoteum.com
  rules:
    - backendRefs:
        - name: kavita
          port: 5000
