apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: harbor
  namespace: harbor
spec:
  parentRefs:
    - name: main-gateway
      namespace: gateway-api-system
  hostnames:
    - harbor.production.k8s.evoteum.com
  rules:
    - backendRefs:
        - name: harbor
          port: 80
