apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: falco
  namespace: falco
  annotations:
    bumpCount: "1"
spec:
  parentRefs:
    - name: main-gateway
      namespace: gateway-api-system
  hostnames:
    - falco.production.k8s.evoteum.com
  rules:
    - backendRefs:
        - name: falco
          port: 8000
