apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  parentRefs:
    - name: main-gateway
      namespace: gateway-api-system
  hostnames:
    - jellyfin.production.k8s.evoteum.com
  rules:
    - backendRefs:
        - name: jellyfin
          port: 8096
